name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub get

      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json ${DART_CREDENTIALS}

      - name: Dry Run
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: true

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: false
