name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.2

      - name: Install dependencies
        run: flutter pub get

      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          ${{ secrets.PUB_CREDENTIALS_JSON }}
          EOF

      - name: Analyse
        run: flutter analyze

      - name: Dry Run
        run: pub publish --dry-run

      - name: Deployment
        run: pub publish --force

