name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.2

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub get

      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json ${DART_CREDENTIALS}

      - name: Dry Run
        run: dart pub publish --dry-run

      - name: Dry Run
        run: dart pub publish -f

