name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub get

      - name: Publish package
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json ${DART_CREDENTIALS}
          dart pub publish -f
